version: '3'

services:

  vtiger:
    build: versions/${version}
    image: javanile/vtiger-dev:${version}
    environment:
      - VT_ENV=dev
      - VT_DEBUG=true
      - MYSQL_HOST=mysql
      - MYSQL_DATABASE=vtiger
      - MYSQL_ROOT_PASSWORD=secret
    volumes:
      ## Project
      - .:/app
      ## Persistence
      - vtiger:/var/lib/vtiger
    ports:
      - 8088:80
      - 9090:9090
    links:
      - mysql
      - phpmyadmin
      - xdebug

  mysql:
    image: javanile/mysql:5.7.28
    command: --sql-mode=
    environment:
      - MYSQL_DATABASE=vtiger
      - MYSQL_ROOT_PASSWORD=secret
    volumes:
      - ./tests/dataset:/dataset:rw
      - mysql:/var/lib/mysql:rw

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - 8089:80
    environment:
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=secret
    links:
      - mysql

  xdebug:
    image: javanile/xdebug
    cap_add: [ 'NET_ADMIN', 'NET_RAW' ]
    restart: on-failure

volumes:
  mysql:
  vtiger:
